import 'package:flutter/material.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Privacy Policy'),
      ),
      body: const SingleChildScrollView(
        padding: EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            _Section(
              title: '1. Introduction',
              children: [
                Text(
                    'Welcome to Fanta F1 (also known as "IDGAF-1"), a fantasy Formula 1 management application developed by Francesco Battaglini ("Developer", "we", "us", or "our").'),
                SizedBox(height: 8),
                Text(
                    'This Privacy Policy describes how we collect, use, store, and share your information when you use the Fanta F1 mobile application ("the App").'),
                SizedBox(height: 8),
                Text(
                    'By using the App, you agree to the collection and use of information in accordance with this policy.'),
              ],
            ),
            _Section(
              title: '2. Data We Collect',
              children: [
                _Subsection(
                  title: '2.1 Information You Provide Directly',
                  points: [
                    'Email address and password — Used for account creation and authentication via Firebase Authentication.',
                    'Display name and profile photo — Set by you during sign-up or later in your account settings.',
                    'Team name and team avatar — Created by you for your fantasy F1 team. Team names and avatar images are visible to other players within the same lobby.',
                    'Lobby name and password — Created when you set up or join a fantasy lobby.',
                    'Fantasy lineup selections — Your driver picks for each race, including driver choices and associated fantasy costs.',
                    'Scores and team points — Calculated from your lineup selections and aggregated across races.',
                  ],
                ),
                _Subsection(
                  title: '2.2 Information Collected Automatically',
                  points: [
                    'Device model — The model name of your device (e.g., "iPhone 15", "Pixel 8") is collected to associate with your push notification registration.',
                    'Firebase Authentication UID — A unique identifier generated by Firebase for your account.',
                    'Push notification tokens — Firebase Cloud Messaging (FCM) device tokens are stored to deliver push notifications. These tokens are mapped to your device model name.',
                  ],
                ),
                _Subsection(
                  title: '2.3 Information We Do NOT Collect',
                  points: [
                    'No analytics or tracking — We do not use any analytics SDKs, crash reporting tools, or user behavior tracking.',
                    'No location data — The App does not request or collect your GPS location.',
                    'No device identifiers — We do not collect IMEI, Android ID, IDFV, IDFA, or any other persistent device identifiers.',
                    'No contacts, calendar, or microphone access — The App does not access your contacts, calendar, or microphone.',
                    'No advertising or tracking — No advertising SDKs or third-party tracking services are used.',
                  ],
                ),
              ],
            ),
            _Section(
              title: '3. How We Use Your Data',
              children: [
                Text('Your data is used solely for the following purposes:'),
                SizedBox(height: 8),
                Text('1. Account management — Authenticating you and maintaining your user profile.'),
                SizedBox(height: 4),
                Text('2. Fantasy gameplay — Storing and managing your team, lobby, lineup selections, scores, and points.'),
                SizedBox(height: 4),
                Text('3. Push notifications — Sending race-related notifications via Firebase Cloud Messaging (you can opt out at any time).'),
                SizedBox(height: 4),
                Text('4. Team avatars — Storing uploaded team avatar images in Firebase Storage.'),
              ],
            ),
            _Section(
              title: '4. Data Storage and Security',
              children: [
                _Subsection(
                  title: '4.1 Firebase Services',
                  points: [
                    'Firebase Authentication — Your email, password (hashed), display name, and photo URL are managed by Firebase Auth.',
                    'Cloud Firestore — Your user profile, teams, lobbies, lineups, and scores are stored in Firestore databases.',
                    'Firebase Storage — Team avatar images are stored in Firebase Cloud Storage.',
                    'Firebase Cloud Messaging — Push notification tokens are managed via FCM.',
                  ],
                ),
                _Subsection(
                  title: '4.2 Security Measures',
                  points: [
                    'Passwords are hashed and stored server-side by Firebase Authentication.',
                    'Access to your data is controlled through Firebase Firestore security rules.',
                    'Team avatar images are stored with user-specific path patterns.',
                  ],
                ),
              ],
            ),
            _Section(
              title: '5. Data Sharing',
              children: [
                Text(
                    'We do not sell, trade, rent, or share your personal information with any third parties, except as described below:'),
                SizedBox(height: 8),
                Text(
                    '- Firebase (Google) — Your data is stored and processed using Firebase services as described in Section 4.'),
                Text(
                    '- Legal requirements — We may disclose your data if required to do so by law or in response to valid requests by public authorities.'),
              ],
            ),
            _Section(
              title: '6. Data Retention',
              children: [
                Text('Your account data is retained as long as your account is active.'),
                SizedBox(height: 8),
                Text(
                    'If you sign out or delete your account, your data will remain in our Firebase databases until you request its deletion.'),
                SizedBox(height: 8),
                Text('Push notification tokens are updated whenever they are refreshed. Old tokens are overwritten.'),
              ],
            ),
            _Section(
              title: '7. Your Rights',
              children: [
                Text('Depending on your location, you may have the following rights regarding your personal data:'),
                SizedBox(height: 8),
                Text('- Access — Request a copy of the personal data we hold about you.'),
                SizedBox(height: 4),
                Text('- Correction — Request correction of inaccurate personal data.'),
                SizedBox(height: 4),
                Text('- Deletion — Request deletion of your account and associated data.'),
                SizedBox(height: 4),
                Text('- Portability — Request transfer of your data in a structured, machine-readable format.'),
                SizedBox(height: 12),
                Text('To exercise any of these rights, contact us at francesco@battaglini.net.'),
                SizedBox(height: 12),
                Text(
                    'To delete your account and all associated data:\n\n'
                    '1. Sign out of the App.\n'
                    '2. Email us at francesco@battaglini.net with the subject line "Account Deletion Request".\n'
                    '3. We will delete your Firebase Auth account and all associated Firestore documents and remove your avatar images from Firebase Storage.',
                ),
              ],
            ),
            _Section(
              title: '8. Children\'s Privacy',
              children: [
                Text(
                    'The App is not directed to children under the age of 13. We do not knowingly collect personal information from children under 13. If we become aware that we have collected personal data from a child under 13, we will take steps to delete that information promptly.'),
              ],
            ),
            _Section(
              title: '9. Push Notifications',
              children: [
                Text(
                    'The App uses Firebase Cloud Messaging to send push notifications. You can opt out of push notifications at any time through your device settings.'),
                SizedBox(height: 8),
                Text('- iOS: Settings → Notifications → Fanta F1 → Toggle off'),
                SizedBox(height: 4),
                Text('- Android: Settings → Apps → Fanta F1 → Notifications → Toggle off'),
                SizedBox(height: 8),
                Text('Opting out will not affect your ability to use the App\'s core features.'),
              ],
            ),
            _Section(
              title: '10. Changes to This Privacy Policy',
              children: [
                Text(
                    'We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy in the App and updating the "Effective Date" at the top of this policy.'),
              ],
            ),
            _Section(
              title: '11. Third-Party Links and Services',
              children: [
                Text(
                    'The App may display images or content loaded from third-party URLs (e.g., F1 driver and circuit images). These third-party services have their own privacy policies, and we are not responsible for their practices.'),
              ],
            ),
            _Section(
              title: '12. Contact Us',
              children: [
                Text('If you have any questions or concerns about this Privacy Policy or our data practices, please contact us at:'),
                SizedBox(height: 8),
                Text('Francesco Battaglini'),
                Text('Email: francesco@battaglini.net'),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class _Section extends StatelessWidget {
  final String title;
  final List<Widget> children;

  const _Section({required this.title, required this.children});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(top: 16.0, bottom: 8.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: Theme.of(context).textTheme.titleLarge?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
          ),
          const SizedBox(height: 8),
          ...children,
        ],
      ),
    );
  }
}

class _Subsection extends StatelessWidget {
  final String title;
  final List<String> points;

  const _Subsection({required this.title, required this.points});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(top: 12.0, bottom: 8.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: Theme.of(context).textTheme.titleSmall?.copyWith(
                  fontWeight: FontWeight.w600,
                ),
          ),
          const SizedBox(height: 4),
          ...points.map((p) => Padding(
                padding: const EdgeInsets.only(bottom: 4.0, left: 8.0),
                child: Text('• $p'),
              )),
        ],
      ),
    );
  }
}
