// Mocks generated by Mockito 5.4.6 from annotations
// in fanta_f1/test/mock/utils.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fanta_f1/helper/time_utils.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TimeUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimeUtils extends _i1.Mock implements _i2.TimeUtils {
  @override
  _i3.Future<DateTime> tryGetNetworkTime() =>
      (super.noSuchMethod(
            Invocation.method(#tryGetNetworkTime, []),
            returnValue: _i3.Future<DateTime>.value(
              _FakeDateTime_0(this, Invocation.method(#tryGetNetworkTime, [])),
            ),
            returnValueForMissingStub: _i3.Future<DateTime>.value(
              _FakeDateTime_0(this, Invocation.method(#tryGetNetworkTime, [])),
            ),
          )
          as _i3.Future<DateTime>);
}
