name: release
run-name: Create releases for Android and iOS
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  run_tests:
    name: Run all tests
    uses: ./.github/workflows/tests.yaml
  build_app:
    name: Build app for Android and iOS
    uses: ./.github/workflows/build.yaml
    needs:
      - run_tests
    secrets:
      keystore: ${{ secrets.KEYSTORE }}
      key_properties: ${{ secrets.KEY_PROPERTIES }}
      play_services: ${{ secrets.GOOGLE_SERVICES }}
      google_service_info_plist: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}
      firebase_options: ${{ secrets.FIREBASE_OPTIONS }}
      apple_development_certificate: ${{ secrets.APPLE_DEVELOPMENT_CERTIFICATE }}
      apple_development_certificate_password: ${{ secrets.APPLE_DEVELOPMENT_CERTIFICATE_PASSWORD }}
      keychain_password: ${{ github.run_id }}
      provisioning_profile: ${{ secrets.BUILD_PROVISION_PROFILE }}
  create_release:
    name: Create releases
    uses: ./.github/workflows/create-new-release.yaml
    permissions:
      contents: write
      pull-requests: read
    needs:
      - build_app
    if: github.event.pull_request.merged == true
  upload_to_testflight:
    name: Upload app to TestFlight
    uses: ./.github/workflows/upload-to-testflight.yaml
    needs:
      - create_release
    secrets:
      appstore_private_key: ${{ secrets.APP_STORE_CONNECT_UPLOAD_KEY_SECRET }}
    permissions:
      contents: read
      pull-requests: read
